baseURL = 'https://aasoftir.github.io/blog/'
languageCode = 'en-us'
title = 'My Blog 📑'
theme = "hugo-ficurinia"
relativeURLs = true
canonifyURLs = true

[Languages]
  [Languages.en]
  baseURL = "https://aasoftir.github.io/blog/"
  languageName = "English"
  contentDir = 'content'
  weight = 1

  [Languages.pr]
  baseURL = "https://aasoftir.github.io/blog/pr/"
  languageName = "Persian"
  contentDir = 'content/pr'
  weight = 2
