name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Debug step to list contents after checkout
      - name: List files after checkout
        run: |
          ls -alh content
          ls -alh public

      # Step 2: Remove posts from the public folder
      - name: Remove old posts from public/content
        run: |
          rm -rf public/content/posts

      # Step 3: Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      # Step 4: Build the site
      - name: Build the site
        run: hugo --minify

      # Debug step to list contents of public folder after build
      - name: List contents of public folder after build
        run: |
          ls -alh public

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
